[params]
[params.hugoSearch]
[params.hugoSearch.Messages]
welcome= "default welcome message. Configure me by setting params.hugoSearch.messages.welcome"
empty= "default empty results message. Configure me by setting params.hugoSearch.messages.noResults"
success= "default success message. Configure me by setting params.hugoSearch.messages.success"

[module]
[module.hugoVersion]
extended = false
min = "0.78.0"
