[module]
[module.hugoVersion]
extended = false
min = "0.78.0"

[params.search.fields]
posts = ["title", "description"]
actors = ["name", "title", "description"]
[params.search]
collection = "actors"
[params.search.messages]
welcome = "default welcome message."
empty = "default empty results message."
success = "default success message."
