baseURL: "http://example.org/"
languageCode: "en-us"
title: Hugo Search

module:
  imports:
    path: "github.com/murrx/hugo-search"
    disabled: false

    mounts:
      - source: "assets/hugoSearch"
        target: "assets/js/hugoSearch"
      - source: "layouts/partials"
        target: "layouts/partials"

outputs:
  page:
    - html
    - json
  section:
    - html
    - json

params:
  searchfields:
    posts:
      - title
      - description
