baseURL: "http://example.org/"
languageCode: "en-us"
title: Hugo Search

module:
  imports:
    path: "github.com/murrx/hugo-search"
    disabled: false

    mounts:
      source: "assets/hugoSearch"
      target: "assets/js/hugoSearch"

params:
  hugoSearch:
    messages:
      welcome: default welcome message. Configure me by setting params.hugoSearch.messages.welcome
      noResults: default empty results message. Configure me by setting params.hugoSearch.messages.noResults
      success: default success message. Configure me by setting params.hugoSearch.messages.success
