baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Search Example"
theme = "etch"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts"
    weight = 10
  [[menu.main]]
    identifier = "actors"
    name = "actors"
    url = "/actors"
    weight = 20

[params]
mainSections = ["actors"]

[module]
[[module.imports]]
path = "github.com/murrx/hugo-search"
disabled = false

[[module.imports.mounts]]
source = "assets/hugoSearch"
target = "assets/js/hugoSearch"

[[module.imports.mounts]]
source = "layouts/partials"
target = "layouts/partials"

[outputs]
page = ["html", "json"]
section = ["html", "json"]