baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Search"

[module]
[[module.imports]]
path = "github.com/murrx/hugo-search"
disabled = false

[[module.imports.mounts]]
source = "assets/hugoSearch"
target = "assets/js/hugoSearch"

[[module.imports.mounts]]
source = "layouts/partials"
target = "layouts/partials"

[outputs]
page = ["html", "json"]
section = ["html", "json"]

# todo: this currently needs to be set in order to configure json generation.
#       do we want to keep this or find another implementation?
[params]
[params.searchfields]
home = ["title", "description"]
